<?php

/**
 * @file
 * Contains srg_twilio.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function srg_twilio_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the srg_twilio module.
    case 'help.page.srg_twilio':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Controls the interface to Twilio') . '</p>';
      return $output;

    default:
  }
}
